import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://placeit.net/login-process?redirect_to=/my_placeit")
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").press("ControlOrMeta+=")
    page.locator("#login_user_email").press("ControlOrMeta+=")
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").fill("Dr3amc@st!")
    page.locator("#login_user_email").press("Tab")
    page.locator("#login_user_password").fill("Coldfusi0n!")
    page.locator("#login_user_password").press("Tab")
    page.get_by_role("link", name="Forgot your password?").press("Enter")
    page.get_by_role("link", name="Forgot your password?").press("Tab")
    page.get_by_role("button", name="Log In").press("Enter")
    page.get_by_role("button", name="Log In").click()
    page.get_by_text("My Downloads × View All My").press("Tab")
    page.get_by_role("button", name="Log In").click()
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").press("ControlOrMeta+a")
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").press("ControlOrMeta+a")
    page.locator("#login_user_email").fill("ej.aston1@gmail")
    page.locator("#login_user_email").press("Tab")
    page.locator("#login_user_password").fill("Dr3amc@st!")
    page.get_by_text("× Invalid email or password.").click()
    page.get_by_text("× Invalid email or password.").press("ControlOrMeta+-")
    page.get_by_role("button", name="Log In").click()
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").fill("ej.aston1@gmail.com")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("button", name="Log In").click()
    page.locator("#password_secret_eye").click()
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").press("ArrowLeft")
    page.locator("#login_user_email").press("ArrowLeft")
    page.locator("#login_user_email").press("ArrowLeft")
    page.locator("#login_user_email").press("ControlOrMeta+Shift+ArrowLeft")
    page.locator("#login_user_email").fill("ej.aston1@outlook.com")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("link", name="Bella Canvas Crop Top Mockup Featuring a Woman With a Glam Rock Style m35870").click()
    page.goto("https://placeit.net/c/mockups/stages/bella-canvas-crop-top-mockup-featuring-a-woman-with-a-glam-rock-style-m35870/editor?draftId=59603239&colorFolder_Crop%20Top%20Color=%23ffffff&customG_0=t7zfkb62b0&draftId=59603239")
    page.locator(".p-icon.p-sm.remove-gray").click()
    page.get_by_role("button", name="750x750px", exact=True).click()
    page.locator("a").filter(has_text="Upload From Your Device").click()
    page.get_by_role("button", name="Insert Image 750x750px").set_input_files("201.png")
    page.locator(".crop-overlay").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
