import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://placeit.net/login-process?redirect_to=/my_placeit")
    page.locator("#login_user_email").fill("Coldfusi0n!")
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").click()
    page.locator("#login_user_email").press("ControlOrMeta+a")
    page.locator("#login_user_email").fill("ej.aston1@outlook.com")
    page.locator("#login_user_email").press("Tab")
    page.locator("#login_user_password").fill("Coldfusi0n!")
    page.locator("#login_user_password").press("Tab")
    page.get_by_role("link", name="Forgot your password?").press("Tab")
    page.get_by_role("button", name="Log In").press("Enter")
    page.get_by_role("button", name="Log In").press("Enter")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("button", name="Accept Cookies").click()
    page.get_by_role("link").filter(has_text="Delete").nth(1).click()
    page.get_by_role("link", name="Mockup of a Happy Short-").click()
    page.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?draftId=59603927&customG_0=t5k94w3f7e&draftId=59603927")
    page.get_by_text("Replace 750x750px").click()
    page.locator("label").filter(has_text="Remove").locator("span").click()
    page.get_by_role("button", name="750x750px", exact=True).click()
    page.locator("a").filter(has_text="Recently Uploaded").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("button", name="750x750px", exact=True).click()
    page.locator("a").filter(has_text="Recently Uploaded").click()
    page.locator("#recentlyUploadedModal").get_by_role("img").first.click()
    page.get_by_text("× × Crop & Trim Crop Reset").press("ControlOrMeta+-")
    page.get_by_role("button", name="Crop").click()
    page.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?draftId=59603927&draftId=59603927&customG_0=t5m7pud6bd")
    page.locator("label").filter(has_text="Remove").locator("span").click()
    page.get_by_role("button", name="750x750px", exact=True).click()
    page.locator("a").filter(has_text="Recently Uploaded").click()
    page.locator("#recentlyUploadedModal").get_by_role("img").first.click()
    page.get_by_role("button", name="Crop").click()
    page.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?draftId=59603927&draftId=59603927&customG_0=t5m7uyb866")
    with page.expect_popup() as page1_info:
        page.get_by_role("button", name="Make a copy").click()
    page1 = page1_info.value
    page1.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?draftId=59603927&customG_0=t5m7uyb866&draftId=59665360")
    page1.get_by_text("Remove", exact=True).click()
    page1.get_by_role("button", name="750x750px", exact=True).click()
    page1.locator("a").filter(has_text="Recently Uploaded").click()
    page1.locator("#item13CGcb").get_by_role("img").click()
    page1.get_by_text("× × Crop & Trim Crop Reset").press("ControlOrMeta+-")
    page1.get_by_role("button", name="Crop").click()
    page1.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?draftId=59603927&draftId=59665360&customG_0=t5m8bf6ca1")
    page1.get_by_role("button", name="Save to").click()
    page1.get_by_role("button", name="Bella+Canvas Front Product").click()
    page1.get_by_role("button", name="Save", exact=True).click()
    with page1.expect_popup() as page2_info:
        page1.get_by_role("button", name="Make a copy").click()
    page2 = page2_info.value
    page2.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?customG_0=t5m8bf6ca1&draftId=59665496")
    page1.close()
    page.close()
    page2.locator("label").filter(has_text="Remove").click()
    page2.get_by_role("button", name="750x750px", exact=True).click()
    page2.locator("a").filter(has_text="Recently Uploaded").click()
    page2.locator("#recentlyUploadedModal").get_by_role("img").nth(2).click()
    page2.locator("body").press("ControlOrMeta+-")
    page2.get_by_role("button", name="Crop").click()
    page2.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?draftId=59665496&customG_0=t5m8rz8a7a")
    page2.get_by_role("button", name="Save to").click()
    page2.get_by_role("button", name="Bella+Canvas Front Product").click()
    page2.get_by_role("button", name="Save", exact=True).click()
    page2.get_by_role("button", name="Move to").click()
    page2.get_by_text("× Select Folder New Folder").click()
    page2.get_by_role("button", name="Close").click()
    with page2.expect_popup() as page3_info:
        page2.get_by_role("button", name="Make a copy").click()
    page3 = page3_info.value
    page3.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?customG_0=t5m8rz8a7a&draftId=59665615")
    page2.close()
    page3.locator("label").filter(has_text="Remove").click()
    page3.get_by_role("button", name="750x750px", exact=True).click()
    page3.locator("a").filter(has_text="Recently Uploaded").click()
    page3.locator("#recentlyUploadedModal").get_by_role("img").nth(2).click()
    page3.get_by_text("× × Crop & Trim Crop Reset").press("ControlOrMeta+-")
    page3.get_by_role("button", name="Crop").click()
    page3.goto("https://placeit.net/c/mockups/stages/mockup-of-a-happy-short-haired-woman-wearing-a-bella-canvas-crop-top-m14385/editor?draftId=59665615&customG_0=t5m8x9dc21")
    page3.get_by_role("button", name="Save to").click()
    page3.get_by_role("button", name="Bella+Canvas Front Product").click()
    page3.get_by_role("button", name="Save", exact=True).click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
